### PR TITLE
Fix for prompt with image. It should display image url + the message

### LINKED ISSUE #6: Images in the prompt don't work
when an image is present in the prompt, the extension will fail to parse the prompt and thus the generated BibTeX code does not have a title.

### PR DESCRIPTION
**Pull request by officialbishowb**
fixes #6

### CODE REVIEW

**Comment by mcquenji** [comment]
how would this approach handle multiple images?

**Comment by officialbishowb** [comment]
I have tested it with only one image. Probably won't work with multiple images. Let me fix it

**Comment by officialbishowb** [comment]
I see it works, but it adds only one image URL. However, I think the image URL is unnecessary as it can't be accessed

**Comment by officialbishowb** [comment]
Should i removed the image url from the citation and add the text prompt only? @mcquenji

**Comment by mcquenji** [comment]
yeah. i'd just parse the text and ignore the images. or perhaps insert a `[Uploaded image]` for each image into the prompt

**Comment by officialbishowb** [comment]
So for 4 images + a prompt, it would be:

> ```
> [Uploaded image]
> [Uploaded image]
> [Uploaded image]
> [Uploaded image]
> ```
> A prompt text

Right?

**Comment by mcquenji** [comment]
yeah, would make the most sense to me

**Comment by officialbishowb** [comment]
So should display x` [Upload image]` (if available) and add the prompt text with a line break

**Review by mcquenji — APPROVED** [review]
seems legit

**Pull request merged**
